app = "panel213"
primary_region = "gru"

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true

  # para debug, que NO se duerma
  auto_stop_machines = "off"
  min_machines_running = 1
