app = "panel213"
primary_region = "gru"

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

[[mounts]]
  source = "paneldata"
  destination = "/app/var"
